### ISSUE TITLE
assigned a hotkey and nothing happened when it was hit.

### ISSUE THREAD

**Issue by searich** [deanishe/alfred-similar-image-search#2] opened 2016-10-06 04:08 UTC

**Comment by deanishe** [comment] 2016-10-06 10:11
You'll need to provide more details than that if you want me to be able to do anything about it. 

What version of Alfred are you running?

What does Alfred's debugger say?

**Comment by searich** [comment] 2016-10-06 12:51
Thanks for your quick reply! 
- os x 10.11.6
- total finder
- alfred 3 

```
Starting debug for 'Google Similar Images'
[2016-10-06 20:40:41][ERROR: action.script] ./call_with_finder_selection.applescript:1120:1121: script error: Expected end of line, etc. but found “"”. (-2741)
```

**Comment by deanishe** [comment] 2016-10-06 21:47
Why'd you close the issue? We haven't fixed it yet!

The problem is that the workflow doesn't support Alfred **3** yet.

Right-click on the workflow in Alfred Preferences and choose "Open in Finder". Then open the `call_with_finder_selection.applescript` script, and change [line 36](https://github.com/deanishe/alfred-similar-image-search/blob/master/src/call_with_finder_selection.applescript#L36) so it says "Alfred 3", not "Alfred 2".

Bob's your uncle.

**Comment by searich** [comment] 2016-10-07 02:20
Sorry, I made a mistake to close the issue.
After revising the script as you noted, I still got this,

```
Starting debug for 'Google Similar Images'

[2016-10-07 10:16:37][ERROR: action.script] Traceback (most recent call last):
  File "url_for_image.py", line 85, in <module>
    sys.exit(main())
  File "url_for_image.py", line 78, in main
    url = similar_images_url(filepath)
  File "url_for_image.py", line 59, in similar_images_url
    output = subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--include', '--silent', '--user-agent', 'alfred-similiar-image-search 0.1 ()', '--form', 'image_url=', '--form', 'filename=', '--form', 'h1=en', '--form', 'bih=179', '--form', 'biw=1600', '--form', 'encoded_image=@/Users/Mac_Ben/Downloads/IMG_7025_1.jpg', 'https://www.google.com/searchbyimage/upload']' returned non-zero exit status 7
```

**Comment by deanishe** [comment] 2016-10-07 05:24
That's a cURL error. [Couldn't connect to host/proxy](https://curl.haxx.se/libcurl/c/libcurl-errors.html).

That's more likely an issue with your connection. Try again later and see if it works.

**Comment by searich** [comment] 2016-10-08 02:53
Can I config the proxy setting within your workflow? I acctually use a proxy to get access Google.

**Comment by deanishe** [comment] 2016-10-08 10:19
The workflow should automatically use the HTTPS proxy you have set in System Preferences.

Otherwise, adding an `https_proxy` Workflow Environment Variable in the workflow configuration sheet should work.

If you're using a SOCKS proxy, you'll have to edit [the workflow code to pass the proxy address to `curl`](https://github.com/deanishe/alfred-similar-image-search/blob/master/src/url_for_image.py#L43).

**Closed as completed** 2019-02-15 12:46 UTC
